return {
	{
		"nvim-treesitter/nvim-treesitter",
		event = { "BufReadPost", "BufNewFile" },
		build = ":TSUpdate",
		cmd = { "TSUpdateSync", "TSUpdate", "TSInstall" },
		main = "nvim-treesitter.configs",
		opts = {
			sync_install = false,
			ensure_installed = {
				"c_sharp",
				"graphql",
				"bash",
				"html",
				"javascript",
				"json",
				"lua",
				"markdown",
				"markdown_inline",
				"python",
				"query",
				"regex",
				"tsx",
				"typescript",
				"vim",
				"yaml",
				"rust",
				"ron",
				"toml",
				"fsharp",
			},
			highlight = { enable = true },
			indent = { enable = true },
		},
	},
}
